### ISSUE TITLE
Webpack configuration does not work with babel 7

### ISSUE THREAD

**Issue by correnson** [electron-userland/electron-webpack#125]
Hello, thanks for this awesome package !

I'd like to use react and additional webpack configuration, which finally makes Babel (7.x) complaining
about unknown `.isPluginRequired` option.

Details:
 - with electron-webpack@2.x.x, using react raises issue #123, which is easy to fix by switching to
@babel/core@7.x.x and adding a `.babelrc` configuration file. But then, adding a webpack configuration makes Babel complaining about unknown `.isPluginRequired` option. Following workarounds provided with issue #123, I tried to switch back to electron-webpack 1.x and babel 6.x ;
 - now with electron-webpack@1.x.x, everything works fine with babel@6.x.x & co, then adding webpack configuration _do_ work, but dev mode no longer hot reload, which is probably related to old issue #68 which is still opened and still apply to version 2.x ;

For now, I must stick on electron-webpack 1.13.0, babel 6 and default entry points configuration.

**Comment by correnson** [comment]
No real need, but the doc says it _shall_ be possible and that we can decide how to layout our project directory. If it is too complicated to make HMR aware of it, no problem, just mention it in the doc :smith

**Comment by loopmode** [comment]
True. It should either work or not be advertised :)

**Comment by hacker112** [comment]
I have a similar problem. I get:

```
ERROR in ./src/renderer/index.js
  Module build failed: ReferenceError: [BABEL] <projectPath>/src/renderer/index.js: Unknown option: .isPluginRequired. Check out http://babeljs.io/docs/usage/options/ for more information about options.
      at buildUnknownError (<projectPath>/node_modules/@babel/core/lib/config/validation/options.js:100:11)
      at <projectPath>/node_modules/@babel/core/lib/config/validation/options.js:86:57
      at Array.forEach (<anonymous>)
      at validate (<projectPath>/node_modules/@babel/core/lib/config/validation/options.js:64:21)
      at <projectPath>/node_modules/@babel/core/lib/config/full.js:251:36
      at cachedFunction (<projectPath>/node_modules/@babel/core/lib/config/caching.js:42:17)
      at loadPresetDescriptor (<projectPath>/node_modules/@babel/core/lib/config/full.js:243:45)
      at <projectPath>/node_modules/@babel/core/lib/config/full.js:68:19
      at Array.map (<anonymous>)
      at recurseDescriptors (<projectPath>/node_modules/@babel/core/lib/config/full.js:66:36)
      at loadFullConfig (<projectPath>/node_modules/@babel/core/lib/config/full.js:112:6)
      at <projectPath>/node_modules/@babel/core/lib/transform.js:28:33
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```
when I try to start the project after upgrading to electron-webpack@2.01. 

I use a custom webpack config for the renderer.
```json
        "renderer": {
            "webpackConfig": "src/webpack.config.js"
        }
```

**Comment by Gvozd** [comment]
Temp workaround
Write it in your webpack.config.js
```js
// temp workaround for https://github.com/electron-userland/electron-webpack/issues/125
const presetEnv = require('@babel/preset-env/lib/index.js');
delete presetEnv.default;
delete presetEnv.isPluginRequired;
delete presetEnv.transformIncludesAndExcludes;
```

**Comment by soederpop** [comment]
@Gvozd can you supply a little more info? 

I'm trying to get this working out of the box, after having installed @babel/preset-react.  

Do I need to create a custom webpack config now to insert this snippet? I'm not familiar with webpack-merge so I'm not exactly sure what to export as a config, just to take advantage of this snippet.

JS

**Comment by soederpop** [comment]
In order to get `@babel/preset-react` working, and to work around this issue with the `@babel/preset-env` here are the modifications i had to make to `node_modules/electron-webpack/out/configurators/js.js`

```javascript
function createBabelLoader(configurator) {
  const presetEnv = require('@babel/preset-env/lib/index.js');
  delete presetEnv.isPluginRequired;
  delete presetEnv.transformIncludesAndExcludes;


  const presets = [[presetEnv, {
    modules: false,
    targets: computeBabelEnvTarget(configurator.isRenderer, configurator.electronVersion)
  }]];

  const plugins = [require("babel-plugin-syntax-dynamic-import")];

  if (configurator.type !== "main" && configurator.hasDependency("element-ui")) {
    plugins.push([require("babel-plugin-component"), [{
      libraryName: "element-ui",
      styleLibraryName: "theme-chalk"
    }]]);
  }

  addBabelItem(presets, configurator.getMatchingDevDependencies({
    includes: ["babel-preset-", "@babel/preset-"],
    excludes: ["babel-preset-env", "@babel/preset-env"]
  }));
```

this includes @Gvozd fix in the comment above, and it also modifies the call to getMatchingDevDependencies to pick up anything starting with `@babel/preset-`.  

This was just an attempt for me to monkey patch and see what the issue really is.  

It does make the project work with `@babel/preset-react` though as expected.

**Comment by soederpop** [comment]
looking at the configuration it exports, I don't see that it sets `babelRc` to false, so babel-loader will probably pick up a local `.babelrc` -- that is encouraging.

I'm not sure if the other plugins `electron-webpack` adds will get merged in or not, or if we lose the specific babel configuration that is applied depending on the target -- when relying on the local .babelrc

only one way to know, so I'll try.

I like how this project figures out the preset-env targets for you based on the electron version and render target, so I'd love to keep that and not have to maintain that in my .babelrc.  (even though it isn't a big deal.)

i'll experiment more and let you know.

**Comment by aromot** [comment]
I tried the temp workaround from @Gvozd.

When I run `electron-webpack dev`, it works fine.
But when I run `yarn compile && electron-builder`, I get the following error:

```
ERROR in ./src/main/index.js
    Module build failed: Error: Must export a default export when using ES6 modules.
        at createDescriptor (D:\wamp64\www\github\electron-webpack-quick-start\node_modules\@babel\core\lib\config\config-descriptors.js:172:13)
        at D:\wamp64\www\github\electron-webpack-quick-start\node_modules\@babel\core\lib\config\config-descriptors.js:106:12
        at Array.map (<anonymous>)
        at createDescriptors (D:\wamp64\www\github\electron-webpack-quick-start\node_modules\@babel\core\lib\config\config-descriptors.js:105:27)
        at createPresetDescriptors (D:\wamp64\www\github\electron-webpack-quick-start\node_modules\@babel\core\lib\config\config-descriptors.js:97:10)
        at D:\wamp64\www\github\electron-webpack-quick-start\node_modules\@babel\core\lib\config\config-descriptors.js:83:14
        at cachedFunction (D:\wamp64\www\github\electron-webpack-quick-start\node_modules\@babel\core\lib\config\caching.js:42:17)
        at presets (D:\wamp64\www\github\electron-webpack-quick-start\node_modules\@babel\core\lib\config\config-descriptors.js:28:68)
        at mergeChainOpts (D:\wamp64\www\github\electron-webpack-quick-start\node_modules\@babel\core\lib\config\config-chain.js:324:68)
        at D:\wamp64\www\github\electron-webpack-quick-start\node_modules\@babel\core\lib\config\config-chain.js:277:7
        at buildRootChain (D:\wamp64\www\github\electron-webpack-quick-start\node_modules\@babel\core\lib\config\config-chain.js:90:27)
        at loadPrivatePartialConfig (D:\wamp64\www\github\electron-webpack-quick-start\node_modules\@babel\core\lib\config\partial.js:51:53)
        at loadFullConfig (D:\wamp64\www\github\electron-webpack-quick-start\node_modules\@babel\core\lib\config\full.js:43:37)
        at D:\wamp64\www\github\electron-webpack-quick-start\node_modules\@babel\core\lib\transform.js:28:33
        at _combinedTickCallback (internal/process/next_tick.js:131:7)
        at process._tickCallback (internal/process/next_tick.js:180:9)
     @ multi ./src/main/index.js
```
I haven't changed the default main/index.js file, here's its content (sorry for the bulk copy/paste):

```
'use strict'

import { app, BrowserWindow } from 'electron'
import * as path from 'path'
import { format as formatUrl } from 'url'

const isDevelopment = process.env.NODE_ENV !== 'production'

// global reference to mainWindow (necessary to prevent window from being garbage collected)
let mainWindow

function createMainWindow() {
  const window = new BrowserWindow()

  if (false && isDevelopment) {
    window.webContents.openDevTools()
  }

  if (isDevelopment) {
      console.log(`http://localhost:${process.env.ELECTRON_WEBPACK_WDS_PORT}`);
    window.loadURL(`http://localhost:${process.env.ELECTRON_WEBPACK_WDS_PORT}`)
  }
  else {
    window.loadURL(formatUrl({
      pathname: path.join(__dirname, 'index.html'),
      protocol: 'file',
      slashes: true
    }))
  }

  window.on('closed', () => {
    mainWindow = null
  })

  window.webContents.on('devtools-opened', () => {
    window.focus()
    setImmediate(() => {
      window.focus()
    })
  })

  return window
}

// quit application when all windows are closed
app.on('window-all-closed', () => {
  // on macOS it is common for applications to stay open until the user explicitly quits
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  // on macOS it is common to re-create a window even after all windows have been closed
  if (mainWindow === null) {
    mainWindow = createMainWindow()
  }
})

// create main BrowserWindow when electron is ready
app.on('ready', () => {
  mainWindow = createMainWindow()
})

```

**Comment by Gvozd** [comment]
@aromot check at latest version of electron-webpack
Would work *without* any workarounds at now
