### ISSUE TITLE
Error: [HMR] Env ELECTRON_HMR_SOCKET_PATH is not set

### ISSUE THREAD

**Issue by elbaro** [electron-userland/electron-webpack#129]
```
yarn dev  // works fine


yarn electron-builder
./dist/linux-unpacked/myapp


A JavaScript error occurred in the main process
Uncaught Exception:
Error: [HMR] Env ELECTRON_HMR_SOCKET_PATH is not set
    at eval (webpack-internal:///./node_modules/electron-webpack/out/electron-main-hmr/main-hmr.js:8:9)
    at Object../node_modules/electron-webpack/out/electron-main-hmr/main-hmr.js (/home/user/myapp/dist/linux-unpacked/resources/app.asar/main.js:752:1)
    at __webpack_require__ (/home/user/myapp/dist/linux-unpacked/resources/app.asar/main.js:687:30)
    at fn (/home/user/myapp/dist/linux-unpacked/resources/app.asar/main.js:72:20)
    at Object.0 (/home/user/myapp/dist/linux-unpacked/resources/app.asar/main.js:808:1)
    at __webpack_require__ (/home/user/myapp/dist/linux-unpacked/resources/app.asar/main.js:687:30)
    at /home/user/myapp/dist/linux-unpacked/resources/app.asar/main.js:739:37
    at Object.<anonymous> (/home/user/myapp/dist/linux-unpacked/resources/app.asar/main.js:742:10)
    at Object.<anonymous> (/home/user/myapp/dist/linux-unpacked/resources/app.asar/main.js:870:3)
    at Module._compile (module.js:569:30)
```

Is there a concept of dev/prod in electron-webpack? HMR should be disabled in packaging.

**Comment by amaurymartiny** [comment]
Workaround: I added `cross-env ELECTRON_HMR_SOCKET_PATH=1` in my npm command, it shows a warning in the console, but Electron does launch.

**Comment by dirkk0** [comment]
I had the same problem with 'yarn dist'.
Actually, it should work, since the 'dist' command is 'yarn compile && electron-builder'.
But I suspect that the windows shells don't support '&&', thus failing in delivering both commands.
Anyhow, 'yarn compile' and 'yarn dist' works on Win10.

**Comment by ufukomer** [comment]
This only happens on Windows 7 for my case while it is working perfectly on Mac, Linux, and Windows 10. Any solution to that?

**Comment by ufukomer** [comment]
Actually, disabling the devtools for production builds fixed my issue.
