### ISSUE TITLE
Error: no schema with key or ref "http://json-schema.org/draft-07/schema#"

### ISSUE THREAD

**Issue by seanzer** [electron-userland/electron-webpack#137]
`read-config-file@3.0.1` seems to cause an issue with electron-webpack. I'm not sure who's issue it is. Using `read-config-file@3.0.0` explicitly works.

The error I get is:
```
Error: no schema with key or ref "http://json-schema.org/draft-07/schema#"
    at validate (E:\electron-quick-start\node_modules\ajv\lib\ajv.js:92:21)
    at validateSchema (E:\electron-quick-start\node_modules\ajv\lib\ajv.js:162:19)
    at _addSchema (E:\electron-quick-start\node_modules\ajv\lib\ajv.js:288:7)
    at Ajv.compile (E:\electron-quick-start\node_modules\ajv\lib\ajv.js:113:21)
    at validateConfig (E:\electron-quick-start\node_modules\read-config-file\src\main.ts:119:25)
    at <anonymous>
From previous event:
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Object.getAppConfiguration (E:\electron-quick-start\node_modules\electron-webpack\src\main.ts:24:26)
```

**Comment by develar** [comment]
Fixed in upcoming 2.1.0
