### ISSUE TITLE
HMR not working with Vue (always doing full reloads)

### ISSUE THREAD

**Issue by lspohn** [electron-userland/electron-webpack#185]
Hi guys,

I set up a project using electron-webpack using Vue.

HMR is enabled but I always get this error:

>  **Cannot apply update. Need to do a full reload!**
> module.exports @ log.js:26
> (anonymous) @ dev-server.js:39
> Promise rejected (async)
> check @ dev-server.js:36
> (anonymous) @ dev-server.js:55
> emitOne @ events.js:116
> emit @ events.js:211
> reloadApp @ index.js?http://localhost:56402:221
> ok @ index.js?http://localhost:56402:134
> onmessage @ socket.js:41
> EventTarget.dispatchEvent @ sockjs.js:170
> (anonymous) @ sockjs.js:887
> SockJS._transportMessage @ sockjs.js:885
> EventEmitter.emit @ sockjs.js:86
> WebSocketTransport.ws.onmessage @ sockjs.js:2961
> log.js?1afd:26 **[HMR] Error: Aborted because ./node_modules/material-design-icons-iconfont/dist/material-design-icons.css** is not accepted
> Update propagation: ./node_modules/material-design-icons-iconfont/dist/material-design-icons.css -> ./src/renderer/index.js -> 0
>     at hotApply (http://localhost:56402/renderer.js:478:30)
>     at http://localhost:56402/renderer.js:316:22
>     at <anonymous>

Happens with any other CSS file, too.

I tried to add "if (module.hot) module.hot.accept()" in my renderer/index.js, and then HMR doesn't do a full reload, but changes in my templates during runtime are not adopted anyway.

Any ideas?

- Electron-webpack: 2.1.2
- Electron-webpack-vue: 2.1.3
- Vue: 2.5.17
- Webpack: 4.16.5

**Comment by tolawho** [comment]
same this

**Comment by lspohn** [comment]
Additional info:

I added a line like this for each css file: 
`if (module.hot) module.hot.accept(['../../node_modules/vuetify/dist/vuetify.min.css'], () => {})`

HMR does not perform any full reload now. **But: Changes are not visible!** Console shows "App hot update" and a lot of updates .vue Files but changes in the source code are only visible after reload via CTRL+R.

Any ideas?

This bug makes developing really nasty for me.

**Comment by tolawho** [comment]
@lspohn I moved my project to Vue ui and i install plugin vue-cli-plugin-electron-builder . HMR work perfect

**Comment by jmeinke** [comment]
lspohn and I have solved this problem by whitelisting the following packages from HMR (in package.json):
`"whiteListedModules": [
      "vuetify",
      "material-design-icons-iconfont",
      "typeface-roboto",
      "typeface-source-sans-pro"
    ]`
