### ISSUE TITLE
dev on Windows   CreateProcess failed with error 193 (no message available)

### ISSUE THREAD

**Issue by mikesi** [electron-userland/electron-webpack#223]
OS: Windows 10
Yarn: 1.12.1
NodeJs: 10.13.0
_yarn compile and build work ok, but running yarn dev fails.
full stack of yarn dev:_
Error: Renderer WDS exited with code 0
    at ChildProcessManager.child.on.code (X:\App\node_modules\electron-webpack\src\dev\ChildProcessManager.ts:62:32)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
From previous event:
    at X:\App\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at startRenderer (X:\App\node_modules\electron-webpack\out\dev\WebpackDevServerManager.js:149:17)
    at X:\App\node_modules\electron-webpack\src\dev\dev-runner.ts:43:7
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at DevRunner.start (X:\App\node_modules\electron-webpack\src\dev\dev-runner.ts:32:14)
    at X:\App\node_modules\electron-webpack\src\dev\dev-runner.ts:142:19
    at Generator.next (<anonymous>)
From previous event:
    at main (X:\App\node_modules\electron-webpack\out\dev\dev-runner.js:132:18)
    at Object.<anonymous> (X:\App\node_modules\electron-webpack\src\dev\dev-runner.ts:145:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at runInDevMode (X:\App\node_modules\electron-webpack\src\cli.ts:35:3)
    at Object._yargs.default.command.command.command.command.command.argv [as handler] (X:\App\node_modules\electron-webpack\src\cli.ts:13:71)
    at Object.runCommand (X:\App\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (X:\App\node_modules\yargs\yargs.js:1059:30)
    at Object.get [as argv] (X:\App\node_modules\yargs\yargs.js:1000:21)
    at Object.<anonymous> (X:\App\node_modules\electron-webpack\src\cli.ts:8:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)

**Comment by scharfark** [comment]
same for me

**Comment by functionwell** [comment]
me either

**Comment by spriggsey** [comment]
To temporarily workaround try to roll back `electron-webpack` to version: `2.3.0`

This allowed me to be able to get dev running again.

**Comment by durdenx** [comment]
Ok thanks @spriggsey! It works.

**Comment by manolinjr81** [comment]
Same here, I'll try @spriggsey solution.

**Comment by PerfectionCSGO** [comment]
Having this issue on 2.3.1 and 2.4.0 as well as 2.5.0. This is possibly because of another package?

```
"dependencies": {
    "mobx": "^5.6.0",
    "mobx-react": "^5.3.6",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-router-dom": "^4.3.1",
    "source-map-support": "^0.5.9"
  },
  "devDependencies": {
    "@babel/preset-react": "^7.0.0",
    "@types/enzyme": "^3.1.15",
    "@types/enzyme-adapter-react-16": "^1.0.3",
    "@types/jest": "^23.3.9",
    "@types/react": "^16.7.6",
    "@types/react-dom": "^16.0.9",
    "@types/react-router-dom": "^4.3.1",
    "electron": "^3.0.9",
    "electron-builder": "^20.34.0",
    "electron-react-devtools": "^0.5.3",
    "electron-webpack": "^2.5.0",
    "electron-webpack-eslint": "^4.0.0",
    "electron-webpack-ts": "^3.0.0",
    "enzyme": "^3.7.0",
    "enzyme-adapter-react-16": "^1.7.0",
    "eslint": "^5.9.0",
    "eslint-config-prettier": "^3.3.0",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-jest": "^22.0.0",
    "eslint-plugin-prettier": "^3.0.0",
    "eslint-plugin-react": "^7.11.1",
    "eslint-plugin-typescript": "^0.13.0",
    "jest": "^23.6.0",
    "jest-enzyme": "^7.0.1",
    "jest-junit": "^5.2.0",
    "less": "^3.8.1",
    "less-loader": "^4.1.0",
    "prettier": "^1.15.2",
    "react-hot-loader": "^4.3.11",
    "rimraf": "^2.6.2",
    "ts-jest": "^23.10.4",
    "typescript": "^3.1.6",
    "typescript-eslint-parser": "^21.0.0",
    "webpack": "^4.25.1"
  },
```

**Comment by Drigtime** [comment]
rolling back electron-webpack to 2.3.1 worked for me, thanks you @spriggsey  ;)
OS: Windows 10
Yarn: 1.12.3
NodeJs: 10.13.0

**Comment by cmeeren** [comment]
Thanks! Works now. 👏
