### ISSUE TITLE
mocha-webpack to use electron-webpack generated webpack config

### ISSUE THREAD

**Issue by wyxos** [electron-userland/electron-webpack#229]
I am trying to configure mocha-webpack to use the webpack.renderer.config.js for unit tests. But I get the following error

```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property '_trace'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?,
resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack >= v2.0.0 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           _trace: …
         }
       })
     ]
    at webpack (D:\code\js\content-manager\node_modules\webpack\lib\webpack.js:31:9)
    at createCompiler (D:\code\js\content-manager\node_modules\mocha-webpack\lib\webpack\compiler\createCompiler.js:15:40)
    at TestRunner.<anonymous> (D:\code\js\content-manager\node_modules\mocha-webpack\lib\runner\TestRunner.js:172:51)
    at eval (eval at processIncludes (D:\code\js\content-manager\node_modules\nodent-runtime\runtime.js:36:12), <anonymous>:3:4725)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! content-manager@1.0.0 test:unit: `mocha-webpack --webpack-config=node_modules/electron-webpack/webpack.renderer.config.js --require=tests/unit/setup.js tests/unit/**/*.spec.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the content-manager@1.0.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Creating a custom webpack.config.js with the following code

```
const webpackRenderer = require('electron-webpack/webpack.renderer.config.js');

module.exports = env => {
  return new Promise((resolve, reject) => {
    /* get provided config */
    webpackRenderer(env).then(config => {
      /* return modified config to webpack */
      resolve(config)
    })
  })
};
```

throws the following error:

```
Module parse failed: Unexpected token (1:0)
  You may need an appropriate loader to handle this file type.
  > <template>
  |     <div>
  |         <div id="heading">Hello world!</div>

```

despite that inspecting the config returned does indeed contain the vue-loader rules and plugin.

**Comment by Jack-Barry** [comment]
Any pointers on this? Would really like to get Mocha up and running with an `electron-webpack` project.

**Comment by Jack-Barry** [comment]
A fix for this has been merged into the [`mochapack`](https://github.com/sysgears/mochapack) library which is the actively maintained version of `mocha-webpack`.

**Comment by wyxos** [comment]
@Jack-Barry Sorry I actually moved away from webpack following release of vite and vue 3. Based on your note I understand this is resolved and will thus close the issue.
