### ISSUE TITLE
Typescript doesn't load *.vue components 

### ISSUE THREAD

**Issue by partap** [electron-userland/electron-webpack#264]
I'm been struggling with this for days...

My issue is that electron-webpack doesn't seem to be able to load *.vue components from a typescript file.  To illustrate the problem, I've forked `electron-webpack-quickstart` [here.](https://github.com/partap/electron-webpack-quick-start)

I've tried to make the minimal changes to to repo in order to reproduce the problem.  Basically, I've added `typescript`, `vue`, `electron-webpack-ts` and `electron-webpack-vue` to the project, and then changed the renderer entry point from `index.js` to `index.ts`.

index.ts:
```
import Vue from "vue"

Vue.config.productionTip = false
Vue.config.devtools = process.env.NODE_ENV === "development"


import App from './App.vue'
new Vue({
  render: h => h(App)
}).$mount('#app')
```

App.vue:
```
<template>
  <div class="app">
    <p> Hello from App.vue HTML template</p>
  </div>
</template>

<script lang="ts">
export default {
  name: 'App',
  components: {},
}
</script>
```

Now if I try to compile it, I get the error: "TS2307: Cannot find module './App.vue'"
```
partap@Clover$ yarn compile                                                                                            master
yarn run v1.13.0
$ electron-webpack
[1] Hash: c9533a9c6758d3f0ca4a23b8967477475ff926f3
Version: webpack 4.28.4
Child
    Hash: c9533a9c6758d3f0ca4a
    Time: 2014ms
    Built at: 2019-01-23 15:59:03
     2 assets
    Entrypoint main = main.js main.js.map
    [0] external "electron" 42 bytes {0} [built]
    [1] external "path" 42 bytes {0} [built]
    [2] external "url" 42 bytes {0} [built]
    [3] multi ./src/main/index.ts 28 bytes {0} [built]
    [4] ./src/main/index.ts 1.51 KiB {0} [built]

    ERROR in /Users/partap/src/electron-webpack-quick-start-vue-ts/src/renderer/index.ts
    [tsl] ERROR in /Users/partap/src/electron-webpack-quick-start-vue-ts/src/renderer/index.ts(10,17)
          TS2307: Cannot find module './App.vue'.
Child
    Hash: 23b8967477475ff926f3
    Time: 3468ms
    Built at: 2019-01-23 15:59:05
     2 assets
    Entrypoint renderer = renderer.js renderer.js.map
    [0] multi ./node_modules/electron-webpack/vue-renderer-entry.js ./src/renderer/index.ts 40 bytes {0} [built]
    [1] ./src/renderer/index.ts 570 bytes {0} [built] [failed] [2 errors]
    [2] ./node_modules/electron-webpack/vue-renderer-entry.js + 1 modules 289 KiB {0} [built]
        |    2 modules

    ERROR in ./src/renderer/index.ts
    Module build failed (from ./node_modules/ts-loader/index.js):
    Error: TypeScript emitted no output for /Users/partap/src/electron-webpack-quick-start-vue-ts/src/renderer/index.ts.
        at makeSourceMapAndFinish (/Users/partap/src/electron-webpack-quick-start-vue-ts/node_modules/ts-loader/dist/index.js:78:15)
        at successLoader (/Users/partap/src/electron-webpack-quick-start-vue-ts/node_modules/ts-loader/dist/index.js:68:9)
        at Object.loader (/Users/partap/src/electron-webpack-quick-start-vue-ts/node_modules/ts-loader/dist/index.js:22:12)
     @ multi ./node_modules/electron-webpack/vue-renderer-entry.js ./src/renderer/index.ts renderer[1]

    ERROR in /Users/partap/src/electron-webpack-quick-start-vue-ts/src/renderer/index.ts
    ./src/renderer/index.ts
    [tsl] ERROR in /Users/partap/src/electron-webpack-quick-start-vue-ts/src/renderer/index.ts(10,17)
          TS2307: Cannot find module './App.vue'.
    Child html-webpack-plugin for "index.html":
         1 asset
        Entrypoint undefined = index.html
        [0] ./node_modules/html-loader/dist/cjs.js?minimize=false&url=false!./dist/.renderer-index-template.html 260 bytes {0} [built]
error Command failed with exit code 2.
```

I've tried to build it with `node --inspect`, putting breakpoints in both `ts-loader` and `vue-loader`, and it seems that `vue-loader` is never called.

On the other hand, if I change `index.ts` back to `index.js`, it compiles and runs with no issue... so I'm guessing it has something to do with how typescript (or ts-loader) resolves `import App from './App.vue'` vs javascript.

I was able to make Vue work with typescript using vue-cli, but the webpack config and rules are so different between that and what I need for electron, that I'm not sure where to start.  I'm new to webpack in general, so I can follow along in a working config, but if there's a problem with it, I can't tell.

**Comment by partap** [comment]
I noticed that vue-cli generates a file in the src root directory: `shims-vue.d.ts`

If I add that file to `src/renderer`, it imports the vue file with no problem.  I don't know what it does, but it works.

shims-vue.d.ts:
```
declare module '*.vue' {
  import Vue from 'vue';
  export default Vue;
}
```
