### ISSUE TITLE
Missing file?

### ISSUE THREAD

**Issue by loopmode** [electron-userland/electron-webpack#27]
When trying to run `yarn dev`, I get the following error. ("Das System kann die angegebene Datei nicht finden." = "System was unable to find the file")

I am on 
- Windows 10 x64
- node 8.5.0 (via nvm)
- yarn 0.24.5
- npm 5.3.0

```
$ yarn dev
yarn dev v0.24.5
$ electron-webpack dev
┏ Renderer -------------------

  CreateProcess failed with error 2: Das System kann die angegebene Datei nicht finden.

┗ ----------------------------
Error: Renderer WDS exited with code 0
    at ChildProcessManager.child.on.code (D:\Projects\electron\electron-webpack-quick-start\node_modules\electron-webpack\src\dev\ChildProcessManager.ts:60:32)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
From previous event:
    at D:\Projects\electron\electron-webpack-quick-start\node_modules\electron-webpack\src\dev\WebpackDevServerManager.ts:47:10
    at Generator.next (<anonymous>)
    at D:\Projects\electron\electron-webpack-quick-start\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at startRenderer (D:\Projects\electron\electron-webpack-quick-start\node_modules\electron-webpack\out\dev\WebpackDevServerManager.js:72:21)
    at D:\Projects\electron\electron-webpack-quick-start\node_modules\electron-webpack\src\dev\dev-runner.ts:37:7
    at Generator.next (<anonymous>)
From previous event:
    at DevRunner.start (D:\Projects\electron\electron-webpack-quick-start\node_modules\electron-webpack\out\dev\dev-runner.js:122:11)
    at D:\Projects\electron\electron-webpack-quick-start\node_modules\electron-webpack\src\dev\dev-runner.ts:131:19
    at Generator.next (<anonymous>)
From previous event:
    at main (D:\Projects\electron\electron-webpack-quick-start\node_modules\electron-webpack\out\dev\dev-runner.js:42:22)
    at Object.<anonymous> (D:\Projects\electron\electron-webpack-quick-start\node_modules\electron-webpack\src\dev\dev-runner.ts:134:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at runInDevMode (D:\Projects\electron\electron-webpack-quick-start\node_modules\electron-webpack\src\cli.ts:37:2)
    at Object.__dirname.default.command.command.command.command.command.argv [as handler] (D:\Projects\electron\electron-webpack-quick-start\node_modules\electron-webpack\src\cli.ts:17:16)
    at Object.self.runCommand (D:\Projects\electron\electron-webpack-quick-start\node_modules\yargs\lib\command.js:233:22)
    at Object.Yargs.self._parseArgs (D:\Projects\electron\electron-webpack-quick-start\node_modules\yargs\yargs.js:990:30)
    at Object.get [as argv] (D:\Projects\electron\electron-webpack-quick-start\node_modules\yargs\yargs.js:927:19)
    at Object.<anonymous> (D:\Projects\electron\electron-webpack-quick-start\node_modules\electron-webpack\src\cli.ts:17:16)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
┏ Main -----------------------

  Hash: 5905c4b8b84576d437f9
  Version: webpack 3.6.0
  Time: 876ms
    Asset     Size  Chunks             Chunk Names
  main.js  37.4 kB       0  [emitted]  main
  [./node_modules/electron-webpack/out/electron-main-hmr/main-hmr.js] ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr.js 559 bytes {0} [built]
  [./src/main/index.js] ./src/main/index.js 1.22 kB {0} [built]
  [electron] external "electron" 42 bytes {0} [not cacheable]
  [electron-webpack/out/electron-main-hmr/HmrClient] external "electron-webpack/out/electron-main-hmr/HmrClient" 42 bytes {0} [not cacheable]
  [source-map-support/source-map-support.js] external "source-map-support/source-map-support.js" 42 bytes {0} [not cacheable]
     [0] multi ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr ./src/main/index.js 40 bytes {0} [built]

┗ ----------------------------
                                                                                                                                                      
```

What's weird is:
- There is no `node_modules\electron-webpack\src` folder at all
- Still it manages to name `src\dev\ChildProcessManager.ts:60:32` with line and column number as the culprit
- What I do have is `node_modules\electron-webpack\src\out\dev\ChildProcessManager.js`, and a `ChildProcessManager.d.ts`

What I would like very much: run `yarn dev` and the dev server starts up! :)
I guess some magic is involved here and it fails to work on my windows machine?

Also, I never intended to use typescript, I have zero eperience with it, and maybe ChildProcessManager.ts

**Comment by loopmode** [comment]
Update:

I uninstalled nvm, and installed a fresh node 8.5.0 directly.
(nvm setups tend to have issues with globally installed modules sometimes)

Now I get a different set of error messages - but at least it starts up!

```
$ yarn dev
yarn dev v1.0.2
$ electron-webpack dev
┏ Renderer -------------------

  AttachConsole failed with error 6: Das Handle ist ung�ltig.

┗ ----------------------------
┏ Main -----------------------

  Hash: 5905c4b8b84576d437f9
  Version: webpack 3.6.0
  Time: 1329ms
    Asset     Size  Chunks             Chunk Names
  main.js  37.4 kB       0  [emitted]  main
  [./node_modules/electron-webpack/out/electron-main-hmr/main-hmr.js] ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr.js 559 bytes {0} [built]
  [./src/main/index.js] ./src/main/index.js 1.22 kB {0} [built]
  [electron] external "electron" 42 bytes {0} [not cacheable]
  [electron-webpack/out/electron-main-hmr/HmrClient] external "electron-webpack/out/electron-main-hmr/HmrClient" 42 bytes {0} [not cacheable]
  [source-map-support/source-map-support.js] external "source-map-support/source-map-support.js" 42 bytes {0} [not cacheable]
     [0] multi ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr ./src/main/index.js 40 bytes {0} [built]

┗ ----------------------------
┏ Renderer -------------------

  Content not from webpack is served from D:\Projects\electron\electron-webpack-quick-start\static, D:\Projects\electron\electron-webpack-quick-start\dist\renderer-dll

┗ ----------------------------
┏ Renderer -------------------

  Hash: 9884dff770cfb03384c1
  Version: webpack 3.6.0
  Time: 3488ms
        Asset       Size  Chunks                    Chunk Names
  renderer.js    1.07 MB       0  [emitted]  [big]  renderer
   index.html  398 bytes          [emitted]
  [./node_modules/ansi-html/index.js] ./node_modules/ansi-html/index.js 4.26 kB {0} [built]
  [./node_modules/electron-webpack/package.json] ./node_modules/electron-webpack/package.json 1.22 kB {0} [built]
  [./node_modules/loglevel/lib/loglevel.js] ./node_modules/loglevel/lib/loglevel.js 6.74 kB {0} [built]
  [./node_modules/sockjs-client/lib/entry.js] ./node_modules/sockjs-client/lib/entry.js 244 bytes {0} [built]
  [./node_modules/strip-ansi/index.js] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
  [./node_modules/webpack-dev-server/client/index.js?http://localhost:9080] (webpack)-dev-server/client?http://localhost:9080 5.83 kB {0} [built]
  [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.6 kB {0} [built]
  [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
  [./node_modules/webpack/hot ^\.\/log$] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
  [./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.61 kB {0} [built]
  [./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 77 bytes {0} [built]
     [0] multi (webpack)-dev-server/client?http://localhost:9080 webpack/hot/dev-server ./src/renderer/index.js 52 bytes {0} [built]
  [./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.31 kB {0} [built]
  [./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.04 kB {0} [built]
  [./src/renderer/index.js] ./src/renderer/index.js 1.72 kB {0} [built]
      + 111 hidden modules
  Child html-webpack-plugin for "index.html":
       1 asset
      [./node_modules/html-loader/index.js?minimize=false!../../../__virtual__/renderer-index.html] ./node_modules/html-loader?minimize=false!/__virtual__/renderer-index.html 394 bytes {0} [built]

┗ ----------------------------
┏ Electron -------------------



┗ ----------------------------
┏ Electron -------------------

  Debugger listening on ws://127.0.0.1:5858/16809fc6-fd6d-4470-944e-31f6d226c336
  For help see https://nodejs.org/en/docs/inspector

┗ ----------------------------
```

**Comment by loopmode** [comment]
I think I'm fine after all. Hope this helps somebody else :)

- The `AttachConsole` error only happened the first time, doesn't happen anymore
- Stopping the process via `ctrl+C` doesn't work properly when using ConEmu as wrapper around the git bash
- It works just fine using git bash directly

So in summary:

- Trouble using wrappers around node (windows nvm) or git bash (ConEmu)
- Just fine with a default node installation
- Just fine using default git bash
