### ISSUE TITLE
Can't resolve 'ejs-html-loader'

### ISSUE THREAD

**Issue by cawa-93** [electron-userland/electron-webpack#3]
I does't use EJS. Only `src/index.ejs`

In v0.10.0 got this error:
```
  ERROR in   Error: Child compilation failed:
    Entry module not found: Error: Can't resolve 'ejs-html-loader' in '/run/media/  alex/LinWin/Develop/command-editor':
    Error: Can't resolve 'ejs-html-loader' in '/run/media/alex/LinWin/Develop/comm  and-editor'
    
    - compiler.js:76 
      [command-editor]/[html-webpack-plugin]/lib/compiler.js:76:16
    
    - Compiler.js:304 compile
      [command-editor]/[webpack]/lib/Compiler.js:304:11
    
    - Compiler.js:520 applyPluginsAsync.err
      [command-editor]/[webpack]/lib/Compiler.js:520:14
    
    - Tapable.js:202 next
      [command-editor]/[tapable]/lib/Tapable.js:202:11
    
    - CachePlugin.js:62 Compiler.<anonymous>
      [command-editor]/[webpack]/lib/CachePlugin.js:62:5
    
    - Tapable.js:206 Compiler.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:206:13
    
    - Compiler.js:517 compilation.seal.err
      [command-editor]/[webpack]/lib/Compiler.js:517:11
    
    - Tapable.js:195 Compilation.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:195:46
    
    - Compilation.js:654 self.applyPluginsAsync.err
      [command-editor]/[webpack]/lib/Compilation.js:654:19
    
    - Tapable.js:195 Compilation.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:195:46
    
    - Compilation.js:645 self.applyPluginsAsync.err
      [command-editor]/[webpack]/lib/Compilation.js:645:11
    
    - Tapable.js:195 Compilation.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:195:46
    
    - Compilation.js:640 self.applyPluginsAsync.err
      [command-editor]/[webpack]/lib/Compilation.js:640:10
    
    - Tapable.js:195 Compilation.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:195:46
    
    - Compilation.js:636 sealPart2
      [command-editor]/[webpack]/lib/Compilation.js:636:9
    
    - Tapable.js:195 Compilation.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:195:46
    
    - Compilation.js:579 Compilation.seal
      [command-editor]/[webpack]/lib/Compilation.js:579:8
    
    - Compiler.js:514 applyPluginsParallel.err
      [command-editor]/[webpack]/lib/Compiler.js:514:17
    
    - Tapable.js:289 
      [command-editor]/[tapable]/lib/Tapable.js:289:11
    
    - Compilation.js:481 _addModuleChain
      [command-editor]/[webpack]/lib/Compilation.js:481:11
    
    - Compilation.js:370 Compilation.errorAndCallback
      [command-editor]/[webpack]/lib/Compilation.js:370:4
    
    - Compilation.js:391 moduleFactory.create
      [command-editor]/[webpack]/lib/Compilation.js:391:12
    
    - From previous event:
    
    - compiler.js:69 Object.compileTemplate
      [command-editor]/[html-webpack-plugin]/lib/compiler.js:69:10
    
    - index.js:47 Compiler.<anonymous>
      [command-editor]/[html-webpack-plugin]/index.js:47:40
    
    - Tapable.js:293 Compiler.applyPluginsParallel
      [command-editor]/[tapable]/lib/Tapable.js:293:14
    
    - Compiler.js:509 applyPluginsAsync.err
      [command-editor]/[webpack]/lib/Compiler.js:509:9
    
    - Tapable.js:195 Compiler.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:195:46
    
    - Compiler.js:502 Compiler.compile
      [command-editor]/[webpack]/lib/Compiler.js:502:8
    
    - Compiler.js:82 compiler.applyPluginsAsync.err
      [command-editor]/[webpack]/lib/Compiler.js:82:18
    
    - Tapable.js:202 next
      [command-editor]/[tapable]/lib/Tapable.js:202:11
    
    - Shared.js:161 Compiler.compilerInvalid
      [command-editor]/[webpack-dev-middleware]/lib/Shared.js:161:5
    
    - Tapable.js:204 next
      [command-editor]/[tapable]/lib/Tapable.js:204:14
    
    - CachePlugin.js:32 Compiler.compiler.plugin
      [command-editor]/[webpack]/lib/CachePlugin.js:32:5
    
    - Tapable.js:206 Compiler.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:206:13
    
    - Compiler.js:47 Watching._go
      [command-editor]/[webpack]/lib/Compiler.js:47:17
    
    - Compiler.js:39 Watching.compiler.readRecords.err
      [command-editor]/[webpack]/lib/Compiler.js:39:9
    
    - Compiler.js:395 Compiler.readRecords
      [command-editor]/[webpack]/lib/Compiler.js:395:11
    
    - Compiler.js:36 new Watching
      [command-editor]/[webpack]/lib/Compiler.js:36:17
    
    - Compiler.js:226 Compiler.watch
      [command-editor]/[webpack]/lib/Compiler.js:226:20
    
    - Shared.js:176 Object.startWatch
      [command-editor]/[webpack-dev-middleware]/lib/Shared.js:176:29
    
    - Shared.js:238 Shared
      [command-editor]/[webpack-dev-middleware]/lib/Shared.js:238:8
    
    - middleware.js:22 module.exports
      [command-editor]/[webpack-dev-middleware]/middleware.js:22:15
    
    - Server.js:68 new Server
      [command-editor]/[webpack-dev-server]/lib/Server.js:68:20
    
    - webpack-dev-server.js:389 startDevServer
      [command-editor]/[webpack-dev-server]/bin/webpack-dev-server.js:389:12
    
    - webpack-dev-server.js:353 processOptions
      [command-editor]/[webpack-dev-server]/bin/webpack-dev-server.js:353:3
    
  
  Child html-webpack-plugin for "index.html":
      
      ERROR in Entry module not found: Error: Can't resolve 'ejs-html-loader' in '/run/media/alex/LinWin/Develop/command-editor'
```
I try install this
```
$ yarn add ejs-html-loader -D
```
And got another error
```
  
  ERROR in   Error: Child compilation failed:
    Module build failed: Error: Cannot find module 'ejs'
    
    - module.js:11 require
      internal/module.js:11:18
    
    - render.js:10 Object.<anonymous>
      [command-editor]/[ejs-html-loader]/lib/render.js:10:12
    
    - module.js:11 require
      internal/module.js:11:18
    
    - index.js:12 Object.<anonymous>
      [command-editor]/[ejs-html-loader]/lib/index.js:12:16
    
    - module.js:11 require
      internal/module.js:11:18
    
    - loadLoader.js:13 loadLoader
      [command-editor]/[loader-runner]/lib/loadLoader.js:13:17
    
    
    - Error: Cannot find module 'ejs'
    
    - module.js:11 require
      internal/module.js:11:18
    
    - render.js:10 Object.<anonymous>
      [command-editor]/[ejs-html-loader]/lib/render.js:10:12
    
    - module.js:11 require
      internal/module.js:11:18
    
    - index.js:12 Object.<anonymous>
      [command-editor]/[ejs-html-loader]/lib/index.js:12:16
    
    - module.js:11 require
      internal/module.js:11:18
    
    - loadLoader.js:13 loadLoader
      [command-editor]/[loader-runner]/lib/loadLoader.js:13:17
    
    
    - compiler.js:76 
      [command-editor]/[html-webpack-plugin]/lib/compiler.js:76:16
    
    - Compiler.js:304 compile
      [command-editor]/[webpack]/lib/Compiler.js:304:11
    
    - Compiler.js:520 applyPluginsAsync.err
      [command-editor]/[webpack]/lib/Compiler.js:520:14
    
    - Tapable.js:202 next
      [command-editor]/[tapable]/lib/Tapable.js:202:11
    
    - CachePlugin.js:62 Compiler.<anonymous>
      [command-editor]/[webpack]/lib/CachePlugin.js:62:5
    
    - Tapable.js:206 Compiler.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:206:13
    
    - Compiler.js:517 compilation.seal.err
      [command-editor]/[webpack]/lib/Compiler.js:517:11
    
    - Tapable.js:195 Compilation.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:195:46
    
    - Compilation.js:654 self.applyPluginsAsync.err
      [command-editor]/[webpack]/lib/Compilation.js:654:19
    
    - Tapable.js:195 Compilation.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:195:46
    
    - Compilation.js:645 self.applyPluginsAsync.err
      [command-editor]/[webpack]/lib/Compilation.js:645:11
    
    - Tapable.js:195 Compilation.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:195:46
    
    - Compilation.js:640 self.applyPluginsAsync.err
      [command-editor]/[webpack]/lib/Compilation.js:640:10
    
    - Tapable.js:195 Compilation.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:195:46
    
    - Compilation.js:636 sealPart2
      [command-editor]/[webpack]/lib/Compilation.js:636:9
    
    - Tapable.js:195 Compilation.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:195:46
    
    - Compilation.js:579 Compilation.seal
      [command-editor]/[webpack]/lib/Compilation.js:579:8
    
    - Compiler.js:514 applyPluginsParallel.err
      [command-editor]/[webpack]/lib/Compiler.js:514:17
    
    - Tapable.js:289 
      [command-editor]/[tapable]/lib/Tapable.js:289:11
    
    - Compilation.js:481 _addModuleChain
      [command-editor]/[webpack]/lib/Compilation.js:481:11
    
    - Compilation.js:452 processModuleDependencies.err
      [command-editor]/[webpack]/lib/Compilation.js:452:13
    
    - next_tick.js:131 _combinedTickCallback
      internal/process/next_tick.js:131:7
    
    - From previous event:
    
    - compiler.js:69 Object.compileTemplate
      [command-editor]/[html-webpack-plugin]/lib/compiler.js:69:10
    
    - index.js:47 Compiler.<anonymous>
      [command-editor]/[html-webpack-plugin]/index.js:47:40
    
    - Tapable.js:293 Compiler.applyPluginsParallel
      [command-editor]/[tapable]/lib/Tapable.js:293:14
    
    - Compiler.js:509 applyPluginsAsync.err
      [command-editor]/[webpack]/lib/Compiler.js:509:9
    
    - Tapable.js:195 Compiler.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:195:46
    
    - Compiler.js:502 Compiler.compile
      [command-editor]/[webpack]/lib/Compiler.js:502:8
    
    - Compiler.js:82 compiler.applyPluginsAsync.err
      [command-editor]/[webpack]/lib/Compiler.js:82:18
    
    - Tapable.js:202 next
      [command-editor]/[tapable]/lib/Tapable.js:202:11
    
    - Shared.js:161 Compiler.compilerInvalid
      [command-editor]/[webpack-dev-middleware]/lib/Shared.js:161:5
    
    - Tapable.js:204 next
      [command-editor]/[tapable]/lib/Tapable.js:204:14
    
    - CachePlugin.js:32 Compiler.compiler.plugin
      [command-editor]/[webpack]/lib/CachePlugin.js:32:5
    
    - Tapable.js:206 Compiler.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:206:13
    
    - Compiler.js:47 Watching._go
      [command-editor]/[webpack]/lib/Compiler.js:47:17
    
  
  Child html-webpack-plugin for "index.html":
      [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs 1.39 kB {0} [built] [failed] [1 error]
      
      ERROR in ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs
      Module build failed: Error: Cannot find module 'ejs'
          at Function.Module._resolveFilename (module.js:485:15)
          at Function.Module._load (module.js:437:25)
          at Module.require (module.js:513:17)
          at require (internal/module.js:11:18)
          at Object.<anonymous> (/run/media/alex/LinWin/Develop/command-editor/node_modules/ejs-html-loader/lib/render.js:10:12)
          at Module._compile (module.js:569:30)
          at Object.Module._extensions..js (module.js:580:10)
          at Module.load (module.js:503:32)
          at tryModuleLoad (module.js:466:12)
          at Function.Module._load (module.js:458:3)
          at Module.require (module.js:513:17)
          at require (internal/module.js:11:18)
          at Object.<anonymous> (/run/media/alex/LinWin/Develop/command-editor/node_modules/ejs-html-loader/lib/index.js:12:16)
          at Module._compile (module.js:569:30)
          at Object.Module._extensions..js (module.js:580:10)
          at Module.load (module.js:503:32)
          at tryModuleLoad (module.js:466:12)
          at Function.Module._load (module.js:458:3)
          at Module.require (module.js:513:17)
          at require (internal/module.js:11:18)
          at loadLoader (/run/media/alex/LinWin/Develop/command-editor/node_modules/loader-runner/lib/loadLoader.js:13:17)
          at iteratePitchingLoaders (/run/media/alex/LinWin/Develop/command-editor/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
```
After installation, one more ...
```
$ yarn add ejs -D 
```
```
  ERROR in   Error: Child compilation failed:
    (Emitted value instead of an instance of Error) ejs-html-loader
    /run/media/alex/LinWin/Develop/command-editor/src/index.ejs:5
        3|   <head>
        4|     <meta charset="utf-8">
     >> 5|     <title><%= htmlWebpackPlugin.options.title %></title>
        6|     <% if (htmlWebpackPlugin.options.nodeModules) { %>
        7|       <!-- Add `node_modules/` to global paths so `require` works prope  rly in development -->
        8|       <script>
    htmlWebpackPlugin is not defined:
    NonErrorEmittedError: (Emitted value instead of an instance of Error) ejs-html  -loader
    /run/media/alex/LinWin/Develop/command-editor/src/index.ejs:5
        3|   <head>
        4|     <meta charset="utf-8">
     >> 5|     <title><%= htmlWebpackPlugin.options.title %></title>
        6|     <% if (htmlWebpackPlugin.options.nodeModules) { %>
        7|       <!-- Add `node_modules/` to global paths so `require` works prope  rly in development -->
        8|       <script>
    htmlWebpackPlugin is not defined
    
    - compiler.js:76 
      [command-editor]/[html-webpack-plugin]/lib/compiler.js:76:16
    
    - Compiler.js:304 compile
      [command-editor]/[webpack]/lib/Compiler.js:304:11
    
    - Compiler.js:520 applyPluginsAsync.err
      [command-editor]/[webpack]/lib/Compiler.js:520:14
    
    - Tapable.js:202 next
      [command-editor]/[tapable]/lib/Tapable.js:202:11
    
    - CachePlugin.js:62 Compiler.<anonymous>
      [command-editor]/[webpack]/lib/CachePlugin.js:62:5
    
    - Tapable.js:206 Compiler.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:206:13
    
    - Compiler.js:517 compilation.seal.err
      [command-editor]/[webpack]/lib/Compiler.js:517:11
    
    - Tapable.js:195 Compilation.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:195:46
    
    - Compilation.js:654 self.applyPluginsAsync.err
      [command-editor]/[webpack]/lib/Compilation.js:654:19
    
    - Tapable.js:195 Compilation.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:195:46
    
    - Compilation.js:645 self.applyPluginsAsync.err
      [command-editor]/[webpack]/lib/Compilation.js:645:11
    
    - Tapable.js:195 Compilation.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:195:46
    
    - Compilation.js:640 self.applyPluginsAsync.err
      [command-editor]/[webpack]/lib/Compilation.js:640:10
    
    - Tapable.js:195 Compilation.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:195:46
    
    - Compilation.js:636 sealPart2
      [command-editor]/[webpack]/lib/Compilation.js:636:9
    
    - Tapable.js:195 Compilation.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:195:46
    
    - Compilation.js:579 Compilation.seal
      [command-editor]/[webpack]/lib/Compilation.js:579:8
    
    - Compiler.js:514 applyPluginsParallel.err
      [command-editor]/[webpack]/lib/Compiler.js:514:17
    
    - Tapable.js:289 
      [command-editor]/[tapable]/lib/Tapable.js:289:11
    
    - Compilation.js:481 _addModuleChain
      [command-editor]/[webpack]/lib/Compilation.js:481:11
    
    - Compilation.js:452 processModuleDependencies.err
      [command-editor]/[webpack]/lib/Compilation.js:452:13
    
    - next_tick.js:131 _combinedTickCallback
      internal/process/next_tick.js:131:7
    
    - From previous event:
    
    - compiler.js:69 Object.compileTemplate
      [command-editor]/[html-webpack-plugin]/lib/compiler.js:69:10
    
    - index.js:47 Compiler.<anonymous>
      [command-editor]/[html-webpack-plugin]/index.js:47:40
    
    - Tapable.js:293 Compiler.applyPluginsParallel
      [command-editor]/[tapable]/lib/Tapable.js:293:14
    
    - Compiler.js:509 applyPluginsAsync.err
      [command-editor]/[webpack]/lib/Compiler.js:509:9
    
    - Tapable.js:195 Compiler.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:195:46
    
    - Compiler.js:502 Compiler.compile
      [command-editor]/[webpack]/lib/Compiler.js:502:8
    
    - Compiler.js:82 compiler.applyPluginsAsync.err
      [command-editor]/[webpack]/lib/Compiler.js:82:18
    
    - Tapable.js:202 next
      [command-editor]/[tapable]/lib/Tapable.js:202:11
    
    - Shared.js:161 Compiler.compilerInvalid
      [command-editor]/[webpack-dev-middleware]/lib/Shared.js:161:5
    
    - Tapable.js:204 next
      [command-editor]/[tapable]/lib/Tapable.js:204:14
    
    - CachePlugin.js:32 Compiler.compiler.plugin
      [command-editor]/[webpack]/lib/CachePlugin.js:32:5
    
    - Tapable.js:206 Compiler.applyPluginsAsyncSeries
      [command-editor]/[tapable]/lib/Tapable.js:206:13
    
    - Compiler.js:47 Watching._go
      [command-editor]/[webpack]/lib/Compiler.js:47:17
    
    - Compiler.js:39 Watching.compiler.readRecords.err
      [command-editor]/[webpack]/lib/Compiler.js:39:9
    
    - Compiler.js:395 Compiler.readRecords
      [command-editor]/[webpack]/lib/Compiler.js:395:11
    
    - Compiler.js:36 new Watching
      [command-editor]/[webpack]/lib/Compiler.js:36:17
    
    - Compiler.js:226 Compiler.watch
      [command-editor]/[webpack]/lib/Compiler.js:226:20
    
    - Shared.js:176 Object.startWatch
      [command-editor]/[webpack-dev-middleware]/lib/Shared.js:176:29
    
    - Shared.js:238 Shared
      [command-editor]/[webpack-dev-middleware]/lib/Shared.js:238:8
    
    - middleware.js:22 module.exports
      [command-editor]/[webpack-dev-middleware]/middleware.js:22:15
    
    - Server.js:68 new Server
      [command-editor]/[webpack-dev-server]/lib/Server.js:68:20
    
    - webpack-dev-server.js:389 startDevServer
      [command-editor]/[webpack-dev-server]/bin/webpack-dev-server.js:389:12
    
    - webpack-dev-server.js:353 processOptions
      [command-editor]/[webpack-dev-server]/bin/webpack-dev-server.js:353:3
    
  
  Child html-webpack-plugin for "index.html":
      [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs 0 bytes {0} [built] [1 error]
      
      ERROR in ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs
      (Emitted value instead of an instance of Error) ejs-html-loader
      /run/media/alex/LinWin/Develop/command-editor/src/index.ejs:5
          3|   <head>
          4|     <meta charset="utf-8">
       >> 5|     <title><%= htmlWebpackPlugin.options.title %></title>
          6|     <% if (htmlWebpackPlugin.options.nodeModules) { %>
          7|       <!-- Add `node_modules/` to global paths so `require` works properly in development -->
          8|       <script>
      
      htmlWebpackPlugin is not defined
  Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/vuetify/dist/vuetify.min.css:
```

**Comment by FantasticFiasco** [comment]
I'm having the same problem with `ejs-html-loader`.

I was comparing my code to [Electrify](https://github.com/electron-userland/electrify) and couldn't figure out why Electrify can compile and I can't. Guess it has to be, as you point out, something with the latest version of `electron-webpack`.

**Comment by develar** [comment]
> index.ejs

You don't need this file anymore.

Anyway, error will be fixed.

**Comment by FantasticFiasco** [comment]
> You don't need this file anymore.

So the logic in that file is now handled internally in `electron-webpack`?

**Comment by develar** [comment]
Fixed in `0.10.1`.

> is now handled internally in electron-webpack?

https://github.com/electron-userland/electron-webpack/releases/tag/v0.9.0 "default index renderer file"

**Comment by FantasticFiasco** [comment]
I've noticed that `index.html` get generated automatically, but what I've been trying to figure out is how to get the title of the main window to anything else than the npm package name.

**Comment by develar** [comment]
> to show anything else than the npm package name.

Pass `title` to https://github.com/electron/electron/blob/master/docs/api/browser-window.md when windows is created.

**Comment by cawa-93** [comment]
@develar A few days ago I raised this issue in the slack. When you create a `BrowserWindow`, title set from parameters, but then, it is overridden by the value from the `<title>` tag.
I correctly understood that now there is no way to manage the template index.html?

**Comment by develar** [comment]
I will check this case. `title` param should win.

> I correctly understood that now there is no way to manage the template index.html if index.ejs don't need anymore?

`index.ejs` as in the original vue electron boilerplate is supported. Default template is used when no `index.ejs` If you want customise title — I will option for that.

**Comment by develar** [comment]
Now `productName` option from electron-builder is respected.

**Comment by cawa-93** [comment]
@FantasticFiasco Perhaps you will be useful. In my case, I wanted to set the header from the main process and do not change it later. So I used this code
```js
mainWindow = new BrowserWindow({
	title: `${app.getName()} v${app.getVersion()}`,
})

mainWindow.on('page-title-updated', (event) => {
	event.preventDefault()
})
```

**Comment by develar** [comment]
`title` option is ignored because html contains `title` and, logically, on page load new title is applied.

**Comment by FantasticFiasco** [comment]
@develar I'll give it a try this evening and will get back to you with the outcome. Thanks for putting the effort in fixing this!

**Comment by develar** [comment]
I think, we should _do not_ add `title` tag in the html template.

Because:

1. `title` option doesn't work — user need to know about `page-title-updated` trick.
2. in the production mode (packed), title defaults to your app name (electron-builder correctly sets properties).

So, the only drawback, — in the development mode title defaults to `Electron`. But, often, you in any case explicitly set title to something app specific (app version, or project info, and so on).

**Comment by cawa-93** [comment]
@develar I trued. Window has "index.html" as title

**Comment by develar** [comment]
@cawa-93 In my case removing `title` tag works as expected — `title` option is respected now. I am going to release this fix. Or do you mean that it doesn't work for you (можно обсудить в слаке)?

**Comment by cawa-93** [comment]
I can not tell you in detail, because I did not test it in detail. But a few days ago, in search of a way to set and not change the title from the main process, I tried to use the `index .ejs` without a `<title>` tag. After loading the window, the title was set as an "index.html". And I left in search of another solution.

**Comment by cawa-93** [comment]
I raised this issue in the slack. In the same place I was told the solution -
 https://atomio.slack.com/archives/C044E597S/p1501517367608209

**Comment by FantasticFiasco** [comment]
I've verified that version 0.10.3 fixes my problem, the title is no longer changed to the npm package name. Again, than you for all your help.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-webpack/wiki/Options#browser-window-title

**Comment by FantasticFiasco** [comment]
> title String (optional) - Default window title. Set to true to automatically set to package name (or product name in the electron-builder).

Second word, shouldn't it be `Boolean` instead of `String`?
