### ISSUE TITLE
Error: spawn node-pre-gyp ENOENT

### ISSUE THREAD

**Issue by peakcary** [electron-userland/electron-webpack#32]
when yarn or npm install and happens
> node install

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-pre-gyp ENOENT
    at exports._errnoException (util.js:1016:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by develar** [comment]
npm -g install node-pre-gyp
