### ISSUE TITLE
Codemirror CSS SyntaxError: Unexpected token '.' 

### ISSUE THREAD

**Issue by iboyperson** [electron-userland/electron-webpack#364]
* **Version**:  `22.5.1`

* **Target**: `linux x86_64`

electron-webpack seems to have an issue with Codemirror's CSS as it issues the below error when I run `yarn start dev`. When building without the react component that uses Codemirror everything works as expected.
```
Uncaught ElectronApp/node_modules/codemirror/lib/codemirror.css:3
.CodeMirror {
^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:84:7)
    at createScript (vm.js:258:10)
    at Object.runInThisContext (vm.js:306:10)
    at Module._compile (internal/modules/cjs/loader.js:884:26)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
```

**Comment by iboyperson** [comment]
Sorry for the bother. Solved the issue by [White-listing Externals](https://webpack.electron.build/configuration#white-listing-externals). I will include below what fixed it.

`"whiteListedModules": ["codemirror", "vickymd"]`

**Comment by umerdev228** [comment]
@tjquillan I'm using ViteJs instead of webpack, what should I do ???
