### ISSUE TITLE
No notifications when using webpack-build-notifier

### ISSUE THREAD

**Issue by FantasticFiasco** [electron-userland/electron-webpack#4]
I do not get any notifications on Windows 10 when using `webpack-build-notifier`. For reference see [my branch](https://github.com/FantasticFiasco/axis-searchlight/tree/chore/webpack-build-notifier).

Has it anything to do with [Within Electron Packaging](https://github.com/mikaelbr/node-notifier#within-electron-packaging) or [Using Webpack](https://github.com/mikaelbr/node-notifier#using-webpack)?

**Comment by develar** [comment]
You will get notification only on failure or first success after failure. Do you expect notification on first success?

**Comment by FantasticFiasco** [comment]
I expected to get a notification of this, but got none:

```
┏ Renderer -------------------

  Error: listen EADDRINUSE 127.0.0.1:9080
      at Object.exports._errnoException (util.js:1022:11)
      at exports._exceptionWithHostPort (util.js:1045:20)
      at Server.setupListenHandle [as _listen2] (net.js:1315:14)
      at listenInCluster (net.js:1363:12)
      at GetAddrInfoReqWrap.doListen (net.js:1489:7)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:96:10)

┗ ----------------------------
┏ Renderer -------------------

  webpackDevServer process exited with code 1

┗ ----------------------------
Error: webpackDevServer process exited with code 1
    at ChildProcess.devServerProcess.on.code (C:\code\axis-searchlight\node_modules\electron-webpack\src\dev\WebpackDevServerManager.ts:86:16)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
From previous event:
    at startRenderer (C:\code\axis-searchlight\node_modules\electron-webpack\src\dev\WebpackDevServerManager.ts:24:3)
    at C:\code\axis-searchlight\node_modules\electron-webpack\src\dev\dev-runner.ts:37:7
    at Generator.next (<anonymous>)
From previous event:
    at DevRunner.start (C:\code\axis-searchlight\node_modules\electron-webpack\src\dev\dev-runner.js:122:11)
    at C:\code\axis-searchlight\node_modules\electron-webpack\src\dev\dev-runner.ts:128:19
    at Generator.next (<anonymous>)
From previous event:
    at main (C:\code\axis-searchlight\node_modules\electron-webpack\src\dev\dev-runner.js:42:22)
    at Object.<anonymous> (C:\code\axis-searchlight\node_modules\electron-webpack\src\dev\dev-runner.ts:131:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at runInDevMode (C:\code\axis-searchlight\node_modules\electron-webpack\src\cli.ts:33:2)
    at Object.__dirname.default.command.command.command.command.command.argv [as handler] (C:\code\axis-searchlight\node_modules\electron-webpack\src\cli.ts:17:16)
    at Object.self.runCommand (C:\code\axis-searchlight\node_modules\yargs\lib\command.js:233:22)
    at Object.Yargs.self._parseArgs (C:\code\axis-searchlight\node_modules\yargs\yargs.js:990:30)
    at Object.get [as argv] (C:\code\axis-searchlight\node_modules\yargs\yargs.js:927:19)
    at Object.<anonymous> (C:\code\axis-searchlight\node_modules\electron-webpack\src\cli.ts:17:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

But perhaps this error comes to early, perhaps I only should expect notifications once Webpack has successfully build the app once?

**Comment by develar** [comment]
Yes, currently, only webpack errors are handled by notifier. Not electron-webpack errors.

**Comment by FantasticFiasco** [comment]
Got it, my bad!

**Comment by develar** [comment]
Do you use `0.10.3`? I hope "listen EADDRINUSE 127.0.0.1:9080" should be gone, since now we correctly handle all possible cases of node exit and close webpack dev server. But you use windows.... yeach.... on windows graceful shutdown is not possible using node API and some special  win-only solution is required. Feel free to file issue if such errors occurred often.

**Comment by FantasticFiasco** [comment]
I use `0.11.0`, but as you state I'm on Windows. I keep the task manager open and kill Node processes now and again. I am not to worried over it.
