### ISSUE TITLE
NAPI Addon How it works in electron-wepack

### ISSUE THREAD

**Issue by zacard-orc** [electron-userland/electron-webpack#464]
"electron-builder": "^22.4.1",

    "electron": "18.0.1",
    "electron-builder": "^22.4.1",
    "electron-is-dev": "^1.2.0",
    "electron-updater": "^4.6.5",
    "electron-webpack": "^2.8.2",
    "electron-webpack-ts": "^4.0.1",

    "electron-builder": "^22.4.1",

electron-webpack dev

when i add napi addon into electron main.js,  the app throw an error and can't run
but it works in a pure simple electron project?
How can. i fix it?

┏ Electron -------------------

  App threw an error during load

┗ ----------------------------
┏ Electron -------------------

  TypeError: Cannot read properties of undefined (reading 'indexOf')
      at Function.getFileName (/Users/macbookpro/Documents/mylab/react-play/tmphtml/electron_v2/node_modules/bindings/bindings.js:179:16)
      at bindings (/Users/macbookpro/Documents/mylab/react-play/tmphtml/electron_v2/node_modules/bindings/bindings.js:82:48)
      at Module.eval (webpack-internal:///./src/main/index.js:18:62)
      at eval (webpack-internal:///./src/main/index.js:86:30)
      at Module../src/main/index.js (/Users/macbookpro/Documents/mylab/react-play/tmphtml/electron_v2/dist/main/main.js:3909:1)
      at __webpack_require__ (/Users/macbookpro/Documents/mylab/react-play/tmphtml/electron_v2/dist/main/main.js:703:30)
      at fn (/Users/macbookpro/Documents/mylab/react-play/tmphtml/electron_v2/dist/main/main.js:78:20)
      at Object.0 (/Users/macbookpro/Documents/mylab/react-play/tmphtml/electron_v2/dist/main/main.js:3945:18)
      at __webpack_require__ (/Users/macbookpro/Documents/mylab/react-play/tmphtml/electron_v2/dist/main/main.js:703:30)
      at /Users/macbookpro/Documents/mylab/react-play/tmphtml/electron_v2/dist/main/main.js:770:37

**Comment by zacard-orc** [comment]
And I used the easyest napi demo hello-world , just like :
https://github.com/BugbearR/node-napi-hello.git
