### ISSUE TITLE
dll compilation is broken

### ISSUE THREAD

**Issue by walleXD** [electron-userland/electron-webpack#58]
Hey all,

My attempts at compiling dll break with the following error:
```
/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276
        throw new Error(
Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276:15)
    at SourceMapGenerator_addMapping [as addMapping] (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:110:12)
    at /Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:72:17
    at Array.forEach (native)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:157:14)
    at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:48:24)
    at SourceMapSource.node (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/webpack-sources/lib/SourceMapSource.js:32:35)
    at SourceMapSource.proto.sourceAndMap (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/webpack-sources/lib/SourceAndMapMixin.js:30:18)
    at getTaskForFile (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/webpack/lib/SourceMapDevToolPlugin.js:33:30)
    at chunk.files.forEach.file (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/webpack/lib/SourceMapDevToolPlugin.js:91:21)
    at Array.forEach (native)
    at /Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/webpack/lib/SourceMapDevToolPlugin.js:89:18
    at Array.forEach (native)
    at Compilation.<anonymous> (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/webpack/lib/SourceMapDevToolPlugin.js:88:12)
    at Compilation.applyPlugins1 (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/tapable/lib/Tapable.js:75:14)
    at self.applyPluginsAsync.err (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/webpack/lib/Compilation.js:670:11)
    at next (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/webpack/lib/ProgressPlugin.js:119:6)
    at next (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.<anonymous> (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/babel-minify-webpack-plugin/dist/index.js:119:11)
    at Compilation.applyPluginsAsyncSeries (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/webpack/lib/Compilation.js:666:10)
    at next (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin.callback (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/webpack/lib/ProgressPlugin.js:115:6)
    at next (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.<anonymous> (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/extract-text-webpack-plugin/dist/index.js:275:11)
    at Compilation.applyPluginsAsyncSeries (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/tapable/lib/Tapable.js:206:13)
    at sealPart2 (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/webpack/lib/Compilation.js:662:9)
    at next (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin (/Volumes/macHome/wahmed/Workspaces/coding/Projects/natter/node_modules/webpack/lib/ProgressPlugin.js:111:6)
```

```json
// electron-webpack.json
"renderer": {
    "webpackConfig": "renderer.webpack.config.js",
    "dll": [
      "react",
      "react-dom",
      "react-native-web",
      "prop-types"
    ]
  }
```

The issue seems to be related to sourcemap generation. Any idea about how to fix it?

**Comment by develar** [comment]
`yarn upgrade` Please specify webpack version.

**Comment by walleXD** [comment]
@develar I am already on the latest release but just incase I ran `yarn upgrade`. I am also on `"webpack": "^3.8.1"`. I tried it out in both a React & Vue project. In both cases dll compilation broke with the same error

**Comment by walleXD** [comment]
@develar it breaks if there are more than 2 packages in for dll

**Comment by loopmode** [comment]
Can you make one single extra bundle/entry in your src and just require or import everything you need in that?

**Comment by walleXD** [comment]
Not necessarily as Webpack manage the `dll` bundle and dynamically hooks up everything while compile the renderer files

**Comment by walleXD** [comment]
@develar spent sometime just playing around with `electron-webpack` and different approaches to setting up project. As things stand, it seems that if the `electron-webpack-starter` is used to setup a project and just `electron-webpack` is upgraded everything works well as the lock file keeps dependencies working but after running `yarn upgrade` webpack production build and dll builds fail because of source map related issue as pointed up in the original post. 

Any thoughts on the best way to upgrade to latest packages without borking webpack builds?

**Comment by alexzaganelli** [comment]
I've the same problem 😕

**Comment by thegrekle** [comment]
Same issue for me as well.

"electron": "^1.7.9",
"electron-builder": "^19.45.5",
electron-webpack@1.11.0,
"webpack": "^3.8.1"

**Comment by alexzaganelli** [comment]
@develar may you need some information to fix it? I really can't do it. 
I've noticed that if the `src/main/main.js` is empty, `yarn compile` it's working, but it's enought  this first line `const { electron, BrowserWindow, app, dialog, shell, Menu, Tray, ipcMain } = require('electron')` to broke the compiling

**Comment by alexzaganelli** [comment]
@walleXD @thegrekle try to use this in `package.json`:

```javascript
"resolutions": {
    "webpack-sources": "1.0.1"
},
```

**Comment by thegrekle** [comment]
That did fix it.  Thanks!!

**Comment by walleXD** [comment]
@alexzaganelli It worked!
@develar Any chances you can pin `webpack-sources@1.0.1` in `electron-webpack`?

**Comment by hugohil** [comment]
Note for others having this issue: this solution seems to only works with `yarn`

**Comment by landon9720** [comment]
```"resolutions": {
    "webpack-sources": "1.0.1"
},```

Seems like a working fix. When will this work-around become no longer necessary?

**Comment by walleXD** [comment]
I don't think there's any concrete fixes in the work in upstream atm. So, there's definitely no fixes in the horizon.

One working solution could be pinning the "webpack-sources" version to "1.0.1" until there's a fix. @develar Any thoughts in this regard?
