### ISSUE TITLE
Production build fails to compile

### ISSUE THREAD

**Issue by walleXD** [electron-userland/electron-webpack#63]
Hey all,

So, I have been trying to test out my electron app in a production setting but the compile fails but the development mode works flawlessly. I am getting errors similar to the one in #58. The error's below:
```
Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276:15)
    at SourceMapGenerator_addMapping [as addMapping] (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:110:12)
    at /Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:72:17
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:157:14)
    at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:48:24)
    at SourceMapSource.node (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/webpack-sources/lib/SourceMapSource.js:32:35)
    at /Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/webpack-sources/lib/ConcatSource.js:37:50
    at Array.map (<anonymous>)
    at ConcatSource.node (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/webpack-sources/lib/ConcatSource.js:36:63)
    at ConcatSource.proto.sourceAndMap (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/webpack-sources/lib/SourceAndMapMixin.js:30:18)
    at getTaskForFile (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/webpack/lib/SourceMapDevToolPlugin.js:33:30)
    at chunk.files.forEach.file (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/webpack/lib/SourceMapDevToolPlugin.js:91:21)
    at Array.forEach (<anonymous>)
    at /Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/webpack/lib/SourceMapDevToolPlugin.js:89:18
    at Array.forEach (<anonymous>)
    at Compilation.<anonymous> (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/webpack/lib/SourceMapDevToolPlugin.js:88:12)
    at Compilation.applyPlugins1 (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/tapable/lib/Tapable.js:75:14)
    at self.applyPluginsAsync.err (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/webpack/lib/Compilation.js:670:11)
    at next (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/webpack/lib/ProgressPlugin.js:119:6)
    at next (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.compilation.plugin (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/webpack/lib/BannerPlugin.js:67:5)
    at next (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.<anonymous> (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/babel-minify-webpack-plugin/dist/index.js:119:11)
    at Compilation.applyPluginsAsyncSeries (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/webpack/lib/Compilation.js:666:10)
    at next (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin.callback (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/webpack/lib/ProgressPlugin.js:115:6)
    at Compilation.applyPluginsAsyncSeries (/Volumes/macHome/wahmed/Workspaces/coding/Projects/universal-react/packages/desktop/node_modules/tapable/lib/Tapable.js:206:13)
error Command failed with exit code 1.
```

I am not using an `electron-webpack.json` file but just a custom `.babelrc`:
```json
{
  "presets": [
    "stage-0",
    "react-native"
  ],
  "plugins": [
    [
      "transform-runtime",
      {
        "polyfill": false,
        "regenerator": true
      }
    ],
    [
      "module-resolver",
      {
        "extensions": [
          ".web.js",
          ".js",
          ".jsx",
          ".mjs"
        ],
        "alias": {
          "react-native": "react-native-web",
          "react/lib/ReactNativePropRegistry": "react-native-web/dist/modules/ReactNativePropRegistry",
          "@universal-react/components": "@universal-react/components/web"
        }
      }
    ]
  ]
}

```

Any idea why the production build is breaking?

Thanks bunch ya'll!

@develar

**Comment by walleXD** [comment]
Compile using the Webpack config files for renderer and main but the app built with `electron-builder` fails to boot as it seems to still be looking for Webpack HMR url:

```
Uncaught Exception:
Error: [HMR] Env ELECTRON_HMR_SOCKET_PATH is not set
    at eval (webpack-internal:///./node_modules/electron-webpack/out/electron-main-hmr/main-hmr.js:6:11)
```

**Comment by walleXD** [comment]
Solution is same as in #58

**Comment by erikkallen** [comment]
this did not solve the issue for me, I had to add
````js 
module.exports = {
  devtool: false
}
````

to webpack.main.additions.js to make it build, the error has moved to babel-minify-webpack-plugin though

**Comment by walleXD** [comment]
I got errors initially after following @alexzaganelli solution but everything worked after I deleted my `node_modules` folder & deleted the `yarn.lock` file & reinstalling all npm modules
