### ISSUE TITLE
css-modules error

### ISSUE THREAD

**Issue by airtoxin** [electron-userland/electron-webpack#89]
Hi, I'm using electron-webpack with import css statement to modularize css(css-modules)

`import styles from './CounterPage.css';`

but it returns undefined and also fetches styles.css file 

```
Uncaught TypeError: Cannot read property 's' of undefined
    at CounterPage.render (webpack-internal:///./src/renderer/containers/CounterPage.tsx:10:82)
    at finishClassComponent (/Users/airtoxin/repositories/ts-electron/node_modules/react-dom/cjs/react-dom.development.js:7873:31)
    at updateClassComponent (/Users/airtoxin/repositories/ts-electron/node_modules/react-dom/cjs/react-dom.development.js:7850:12)
    at beginWork (/Users/airtoxin/repositories/ts-electron/node_modules/react-dom/cjs/react-dom.development.js:8225:16)
    at performUnitOfWork (/Users/airtoxin/repositories/ts-electron/node_modules/react-dom/cjs/react-dom.development.js:10224:16)
    at workLoop (/Users/airtoxin/repositories/ts-electron/node_modules/react-dom/cjs/react-dom.development.js:10288:26)
    at HTMLUnknownElement.callCallback (/Users/airtoxin/repositories/ts-electron/node_modules/react-dom/cjs/react-dom.development.js:542:14)
    at Object.invokeGuardedCallbackDev (/Users/airtoxin/repositories/ts-electron/node_modules/react-dom/cjs/react-dom.development.js:581:16)
    at invokeGuardedCallback (/Users/airtoxin/repositories/ts-electron/node_modules/react-dom/cjs/react-dom.development.js:438:27)
    at renderRoot (/Users/airtoxin/repositories/ts-electron/node_modules/react-dom/cjs/react-dom.development.js:10366:7)
/Users/airtoxin/repositories/ts-electron/node_modules/react-dom/cjs/react-dom.development.js:9747 The above error occurred in the <CounterPage> component:
    in CounterPage (created by Connect(CounterPage))
    in Connect(CounterPage) (created by Route)
    in Route (created by Routes)
    in Switch (created by Routes)
    in Routes (created by App)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by App)
    in Provider (created by App)
    in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ /Users/airtoxin/repositories/ts-electron/node_modules/react-dom/cjs/react-dom.development.js:9747
```

<img width="838" alt="screenshot 2018-01-28 2 31 29" src="https://user-images.githubusercontent.com/2460874/35474568-5bb110a4-03d3-11e8-8f17-d3f35943daa9.png">

My expectation of importing css is processing style-loader and css-loader, but electron-webpack is not.
How to process those loader when css imported?

details: https://github.com/airtoxin/ts-electron/tree/96b12cd127ad2771fffbfb49a84780b0c398bebd

**Comment by airtoxin** [comment]
I'm trying custom webpack configuration, but it doesn't work.


```
// webpack.renderer.additions.js
module.exports = {
  module: {
    rules: [
      {
        test: /\.cssmodule$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: { modules: true }
          }
        ]
      }
    ]
  }
}

```

```
// package.json
  "electronWebpack": {
    "renderer": {
      "webpackConfig": "./webpack.renderer.additions.js"
    }
  },
```

```
import styles from './CounterPage.cssmodule';
console.log("@styles", styles); // undefined
```

**Comment by airtoxin** [comment]
Sorry, it's my fault of importing style.

`import * as styles from './CounterPage.cssmodule';` works fine.
